eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eurekaServiceZone}
  instance:
    hostname: ${hostname}

server:
  port: ${appPort}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: blog-service
          uri: lb://blog-service
          predicates:
            - Path=/blog/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
 
